### ISSUE TITLE
Doesnt seem to update

### ISSUE THREAD

**Issue by Gamullus** [adrianonrails/baruch#14]
I might be wrong but the novels dont seem to be updated or updating.
For example dungeon defense(2 new chapters are out but the app is still behind) 
Is there a problem or a bugg?

**Comment by adrianonrails** [comment]
Hi, I've checked the source where i get the contents and it really stopped
at volume 5 chapter 4, whereas novelupdates says the current chapter is 5.
I'll just manually add it tomorrow morning. This is the problem when the
source that I use also didn't get the right chapters.

Thanks for reporting.

**Comment by adrianonrails** [comment]
Hello, I didn't continue adding it manually as I have seen that my novels
source doesn't retrieve the Dungeon defense chapters which are labeled
"Intermission" or "Prologue". I am not sure if this is really a part of the
series. Also, the past Intermission chapters are also not fetched.
