### ISSUE TITLE
Text inversion not working?

### ISSUE THREAD

**Issue by TheAkatsuki** [adrianonrails/baruch#18]
I've downloaded the latest version and even made sure the chapter was downloaded before trying it. I'm making sure I click apply but everytime I enable and disable color inversion so that I don't have a white background, nothing changes. Anyone else seeing this happen?

**Comment by adrianonrails** [comment]
Newer version of chrome is affected with these one. I will push some fixes later for this.

**Comment by adrianonrails** [comment]
The fix is included in the latest version [https://github.com/adrianonrails/baruch/releases/tag/v0.8.9](https://github.com/adrianonrails/baruch/releases/tag/v0.8.9)

**Comment by TheAkatsuki** [comment]
It's fixed in the update. Thanks and just wanted to say this app is great.
