### ISSUE TITLE
Dark mode for reading/theme?

### ISSUE THREAD

**Issue by j0netzky** [adrianonrails/baruch#19]
I tried to find the dark mode for reading that's shown in the photos but I couldn't see it in the settings. Is it not available yet?

**Comment by adrianonrails** [comment]
It's already implemented.
Here's some screenshots on how to navigate there.

![dark](https://user-images.githubusercontent.com/18593260/38005817-07d01cd4-3275-11e8-91b2-80f8a9a25095.png)
